# params.yaml

preprocess:
  target_column: Global_active_power
  test_split_ratio: 0.2

train:
  features:
  - Global_reactive_power
  - Voltage
  - Global_intensity
  - Sub_metering_1
  - Sub_metering_2
  - Sub_metering_3
  - hour_of_day
  - day_of_week
  - month
  - year
models:
  XGBoostRegressor:
    # --- FIX: Add this _target_ key ---
    _target_: src.train.get_model_instance # This can point to any relevant function
    file_name: xgb_model.pkl
    params:
      objective: reg:squarederror
      n_estimators: 250
      learning_rate: 0.05
      max_depth: 5
      min_child_weight: 5
      gamma: 0.2
      random_state: 42
  RandomForestRegressor:
    # --- FIX: Add this _target_ key ---
    _target_: src.train.get_model_instance
    file_name: rf_model.pkl
    params:
      n_estimators: 200
      max_depth: 10
      min_samples_split: 10
      min_samples_leaf: 4
      max_features: 0.5
      random_state: 42
      n_jobs: -1
  LightGBMRegressor:
    # --- FIX: Add this _target_ key ---
    _target_: src.train.get_model_instance
    file_name: lgbm_model.pkl
    params:
      boosting_type: gbdt
      objective: regression_l1
      n_estimators: 300
      learning_rate: 0.01
      num_leaves: 20
      max_depth: 5
      random_state: 42
      n_jobs: -1

validation:
  plots_dir: metrics/validation_plots
